name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        firebase_api: [default, m]

    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18.x'

      - name: Install dependencies
        run: |
          npm install
          npm install -g firebase-tools
          npm install --save-dev jest

      - name: Set Firebase API key
        run: |
          if [ "${{ matrix.firebase_api }}" = "m" ]; then
            echo "FIREBASE_API_KEY=${{ secrets.FIREBASE_API_KEY_M }}" >> $GITHUB_ENV
          else
            echo "FIREBASE_API_KEY=${{ secrets.FIREBASE_API_KEY }}" >> $GITHUB_ENV
          fi

      - name: Run tests
        run: npm test
        env:
          FIREBASE_API_KEY: ${{ env.FIREBASE_API_KEY }}
