name: CI

on:
  push:
    branches: [ main_Assignment6 ]
  pull_request:
    branches: [ main_Assignment6 ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18.x'

      - name: Install dependencies
        run: |
          npm install
          npm install --save-dev jest cross-env @babel/core @babel/preset-env babel-jest jest-environment-jsdom

      - name: Run tests
        run: npm test
        env:
          FIREBASE_API_KEY: ${{ secrets.FIREBASE_API_KEY }}
          FIREBASE_AUTH_DOMAIN: ${{ secrets.FIREBASE_AUTH_DOMAIN }}
          FIREBASE_PROJECT_ID: ${{ secrets.FIREBASE_PROJECT_ID }}
          NODE_ENV: 'test'
